### ISSUE TITLE
Optional function parameter declared before required parameter

### ISSUE THREAD

**Issue by samwilson** [Krinkle/intuition#158]
"Optional parameter $prefix declared before required parameter $code is implicitly treated as a required parameter"

In `Languages.php`:

```php
static function getFileName( $prefix = 'Language', $code, $suffix = '.php' ) {
```

**Comment by samwilson** [comment]
I'm not sure how to update the files in `intuition/language/mw-classes/` should be updated, given that they're copied from MediaWiki. Is it okay to just pull in the new versions? I sort of imagine that doing so might break things!

**Comment by Krinkle** [comment]
@samwilson There's a limited amount of automation in `/scripts/getLangData.php` in this repo. Afaik the classes were just copied by-hand once or twice. I don't recall if they required modification beyond an indicator in the file header and possibly removal of methods we can't/don't use due to dependencies.

**Comment by samwilson** [comment]
Okay cool, I'll have a go at updating them! Or maybe just fix the issue at hand.
