### ISSUE TITLE
Consider changing the license

### ISSUE THREAD

**Issue by ricordisamoa** [Krinkle/intuition#39]
The Intuition software currently uses the [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/) license (<https://creativecommons.org/licenses/by-sa/3.0/>). This is a good in terms of [freedom](https://freedomdefined.org/Definition), but is not very suitable for distribution of source code. See [https://creativecommons.org/faq](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

Let's relicense the source code of this project under the terms of the MIT license. See <https://opensource.org/licenses/MIT> and <https://choosealicense.com/licenses/mit/>.

----

> It can be hard to combine Intuition with existing software (e.g. sharing code with MediaWiki).
> Even Creative Commons themselves [recommend against using their licenses for software](https://wiki.creativecommons.org/FAQ#Can_I_apply_a_Creative_Commons_license_to_software.3F).
>

**Comment by zhaofengli** [comment]
I concur. The translations may be CC'd, but the program should be released under a appropriate license. I'd strongly recommend against GPL, as non-GPL tools (like reFill which uses BSD) won't be able to use the framework. A less restrictive license, like MIT and BSD, is better.

See also http://choosealicense.com/

**Comment by Krinkle** [comment]
Thanks for bringing this up. Most of my software is released under the MIT license. Intuition is still under CC-BY because that was my default from the Toolserver days. By now, I've relicensed most of my projects under MIT, but I never got around to relicensing Intuition.

No worries about interoperability with regards to GPL, I'm aware of its issues and not a fan either!

It appears translatewiki.net requires all contributions to be CC-BY licensed. However content can be under multiple licenses, and per [translatewiki.net's policy](https://translatewiki.net/wiki/Project:About#Copyright_and_disclaimers), they are willing to multi-license translations under any other free license that may be associated with the open-source project the translations are for.

**Comment by Krinkle** [comment]
Based on output from:
```git shortlog -s -- . ':!language/messages/' ':!language/Domains.php' ':!language/domains.json' ':!language/domainInfo.json' ':!public_html/tools.json' ':!language/langlist.php'
```

Contributors to Intuition source code:

* [ ] ChameleonWiki (@ChameleonWiki )
* [ ] Dan Michael O. Heggø (@danmichaelo)
* [ ] Jan Luca Naumann (@Telev)
* [ ] Kaldari (@kaldari)
* [ ] Platonides
* [x] Timo Tijhof (@Krinkle)

Please comment below (or add a positive reaction to this comment) if you agree to relicense your contributions under the terms of the MIT license.

See also <https://choosealicense.com/licenses/mit/> and <https://opensource.org/licenses/MIT>.

**Comment by kaldari** [comment]
MIT sounds fine with me.

**Comment by danmichaelo** [comment]
Me too!
