### ISSUE TITLE
Namespace classes

### ISSUE THREAD

**Issue by agentphoenix** [Krinkle/intuition#76]
I've been looking to include this package in my project, but every time I pull it in through Composer, it breaks one of my other dependencies and I get a fatal error. The reason it's breaking my application is because your packages dump everything into the global namespace instead of using PSR-4 autoloading. While that may work fine in isolation or in applications with few dependencies, in applications that use a lot of dependencies, it can create problems.

For example, I alias one of my dependencies into the global namespace as `HTML`, but everything stops working the moment I pull Intuition in because the `toollabs-base` package defines an `Html` class in the global namespace. Please switch your package over to PSR-4 autoloading to avoid conflicts with other packages. Thanks!

**Comment by Krinkle** [comment]
@agentphoenix Thanks for your report. I'll add a namespace in the next release. Merely switching to PSR-4 will avoid the fatal error ("class already defined"), but I believe would not solve your issue since it will not be predictable random which one "wins" to trigger the autoloader first. (It would presumably depend which of the two packages comes first in Composer's alphabetical registry.)

**Comment by Krinkle** [comment]
The main thing that caused the fatal were actually the unused classes from the `krinkle/toollabs-base` dependency, which I'll remove entirely per #77.

**Comment by Krinkle** [comment]
Closed with https://github.com/Krinkle/intuition/commit/2cf6d42c992e55443a13e851aa8998cf761fc5de and https://github.com/Krinkle/intuition/commit/fdcabf69616b5a3ac07b0e442c29097d679cef32.
