### ISSUE TITLE
Use PHP 7 argument and return type declarations, possibly in strict mode

### ISSUE THREAD

**Issue by MusikAnimal** [Krinkle/intuition#95]
Now that we are requiring PHP 7+, we could take advantage of [argument type declarations](https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration) and [return type declarations](https://secure.php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration). In conjunction with [strict mode](https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict), I've found these help surface bugs. Strict mode can be a little risky for large, long-standing apps, but it's probably worth it once you fix all the bugs.

I've been using the [Slevomat Coding Standard](https://github.com/slevomat/coding-standard) (for PHPCS) which can check for these things. Everything in Intuition seems well-documented so `phpcbf` should be able to add most of the type declarations for you based on the existing doc blocks.

**Comment by Krinkle** [comment]
There are currently still tools using the `ToolStart.php` entry point, and most of those tools are using the default PHP 5.6 webservice in Toolforge still.

While I accept movement toward PHP 7 patterns, we can't break compat until either those tools migrate to the php7.2 backend on Toolforge or that they use a current/previous version of Intuition via Composer (#101).

I forgot about this when I removed PHP 5 from the test matrix, but I guess we've been lucky so far in that the critical parts still work with PHP 5.

**Comment by MusikAnimal** [comment]
Makes sense. Have we considered deprecating external usage of the entry point? I think we should, for this very reason. At any time the originating application could break. Better they use composer to ensure the Intuition version is tested to be working.

Regardless, it sounds like we're only a month or so away from the default Toolforge grid getting an upgrade to a modern PHP. Right now I think it's 5.5.9.

**Comment by Krinkle** [comment]
Yes, the deprecation and removal of the directory-based entry point is #101.

For tools that load the Intuition library via this disk directory in Toolforge, the conversion to loading it via Composer should be fairly simple.

However, a subset of these tools also has their messages loaded from that directory. If they start using the library via Composer, they should probably also migrate their messages to their own repository. However, this means they'll also need to deploy the updates themselves (right now this this is something I do, which I aim to do at least once a month).

Alternatively, they could keep using the messages by registering the central directory as a local message directory. That means they'd use the local code but central messages. That would be somewhat fragile, so instead of that, I propose we simply freeze the central directory at Toolforge at the current version. That would mean it no longer receives bug fixes and translation updates, but also won't cause breakage.

Then, for any tools that want changes to messages or bug fixes, would be required to update their code to load the Intuition library from Composer, and/or store the messages in their own repository.

In have already done the preparatory work to separate the the old "central" directory from the [Preferences dashboard](https://tools.wmflabs.org/intuition/), by moving its code to a separate repository deployed from a separate directory under that Toolforge account.

**Comment by Krinkle** [comment]
Fixed in https://github.com/Krinkle/intuition/commit/47c5ee2387f75320f6eedf7e1d45370d3d47d809.

**Comment by Krinkle** [comment]
Done in https://github.com/Krinkle/intuition/commit/47c5ee2387f75320f6eedf7e1d45370d3d47d809.
