### ISSUE TITLE
Add banana checker Composer script

### ISSUE THREAD

**Issue by samwilson** [Krinkle/intuition#98]
Would it be a good idea to add a PHP version of https://github.com/wikimedia/grunt-banana-checker to Intuition, so that PHP projects that aren't using Grunt can check message validity? e.g. `./vendor/bin/banana-checker`

**Comment by Krinkle** [comment]
I agree that it would make sense for Intuition to be able to validate its own input, and for that to be available as a PHP-only utility.

However, I think for the short-term, I'd prefer to re-use what we have to reduce additional maintenance overhead. We currently have the convention to add a Gruntfile to every MediaWiki extension written in PHP, which in many cases is solely for banana checker.

I would agree that this is slightly odd, but it does mean we have a precedent for making that trade-off already.

Thoughts?

**Comment by Krinkle** [comment]
I'm still open to this, either in this repo or in the (now, no longer grunt-specific) [banana-checker](https://github.com/wikimedia/banana-checker) repo by also publishing a composer package from there. However, I'm closing this issue for now as it's not currently an enhancement or bug that I see as a needed element for the Intuition roadmap. We've also since pretty much accepted use of nodejs-based dev tooling in most of Wikimedia's repos regardless of whether they are themselves a Node.js program.
